// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.marketplace.release-content-directory@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:5205ce85503a52e9d2d50981f989b75c07eac683bd7afac168da8b6ec04fc773";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const RELEASE_CONTENT_DIRECTORY_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const RELEASE_CONTENT_DIRECTORY_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const RELEASE_CONTENT_DIRECTORY_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const RELEASE_CONTENT_DIRECTORY_CONTRACT: CapabilityReference<ReleaseContentDirectoryClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_release_content_directory { () => { "{\"capability_id\":\"lenso.marketplace.release-content-directory@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"read_release_content\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_release_content_directory_client {
    () => { "{\"capability_id\":\"lenso.marketplace.release-content-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.marketplace.release-content-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_release_content_directory_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.marketplace.release-content-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_release_content_directory_client {
    () => { "{\"capability_id\":\"lenso.marketplace.release-content-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.marketplace.release-content-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const READ_RELEASE_CONTENT_OPERATION: &str = "read_release_content";

pub use lenso_contract_runtime::{RawJson, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadReleaseContentRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadReleaseContentResponse {
    #[serde(rename = "envelope_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub envelope_json: RawJson,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadReleaseContentError {
    NotPublished,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct ReleaseContentDirectory;
impl RequestCapability for ReleaseContentDirectory {
    type Request = ReadReleaseContentRequest;
    type Response = ReadReleaseContentResponse;
    type DomainError = ReadReleaseContentError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_RELEASE_CONTENT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ReleaseContentDirectoryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read_release_content(context, request)
    }
}

impl serde::Serialize for ReadReleaseContentError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::NotPublished => serializer.serialize_str("not_published"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadReleaseContentError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "not_published" => Ok(Self::NotPublished),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_read_release_content_request(value: &ReadReleaseContentRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_release_content_request(wire: &str) -> Result<ReadReleaseContentRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_release_content_response(value: &ReadReleaseContentResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_release_content_response(wire: &str) -> Result<ReadReleaseContentResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_release_content_error(value: &ReadReleaseContentError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_release_content_error(wire: &str) -> Result<ReadReleaseContentError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoReleaseContentDirectoryReadReleaseContentResult {
    fn __lenso_into_result(self) -> Result<Result<ReadReleaseContentResponse, ReadReleaseContentError>, RuntimeFailure>;
}
impl __LensoIntoReleaseContentDirectoryReadReleaseContentResult for Result<ReadReleaseContentResponse, ReadReleaseContentError> {
    fn __lenso_into_result(self) -> Result<Result<ReadReleaseContentResponse, ReadReleaseContentError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoReleaseContentDirectoryReadReleaseContentResult for Result<Result<ReadReleaseContentResponse, ReadReleaseContentError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadReleaseContentResponse, ReadReleaseContentError>, RuntimeFailure> { self }
}
impl __LensoIntoReleaseContentDirectoryReadReleaseContentResult for Result<ReadReleaseContentResponse, lenso_plugin_authoring::PluginError<ReadReleaseContentError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadReleaseContentResponse, ReadReleaseContentError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoReleaseContentDirectoryReadReleaseContentResult for Result<ReadReleaseContentResponse, ReleaseContentDirectoryInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadReleaseContentResponse, ReadReleaseContentError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ReleaseContentDirectoryInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ReleaseContentDirectoryInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait ReleaseContentDirectoryProvider: fmt::Debug + 'static {
    fn read_release_content(&self, context: InvocationContext, request: ReadReleaseContentRequest) -> NativeRequestFuture<ReleaseContentDirectory>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_release_content_directory {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportReleaseContentDirectory;
        impl $crate::ReleaseContentDirectoryProvider for $plugin {
        fn read_release_content(&self, context: __LensoNativeSupportReleaseContentDirectory::InvocationContext, request: $crate::ReadReleaseContentRequest) -> __LensoNativeSupportReleaseContentDirectory::NativeRequestFuture<$crate::ReleaseContentDirectory> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read_release_content(&plugin, context, request).await;
                $crate::__LensoIntoReleaseContentDirectoryReadReleaseContentResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_release_content_directory {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportReleaseContentDirectory;
        impl $crate::ReleaseContentDirectoryProvider for $object {
        fn read_release_content(&self, context: __LensoNativeSupportReleaseContentDirectory::InvocationContext, request: $crate::ReadReleaseContentRequest) -> __LensoNativeSupportReleaseContentDirectory::NativeRequestFuture<$crate::ReleaseContentDirectory> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::read_release_content(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoReleaseContentDirectoryReadReleaseContentResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_release_content_directory {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportReleaseContentDirectory;
        impl $crate::ReleaseContentDirectoryProvider for $object {
        fn read_release_content(&self, context: __LensoNativeSupportReleaseContentDirectory::InvocationContext, request: $crate::ReadReleaseContentRequest) -> __LensoNativeSupportReleaseContentDirectory::NativeRequestFuture<$crate::ReleaseContentDirectory> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::ReleaseContentDirectoryProvider>::read_release_content(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct ReleaseContentDirectoryRequestEndpoint { provider: Rc<dyn ReleaseContentDirectoryProvider> }

#[derive(Debug)]
pub struct ReleaseContentDirectoryEndpoint<P: ReleaseContentDirectoryProvider> { provider: Rc<P>, request_endpoint: ReleaseContentDirectoryRequestEndpoint }
impl<P: ReleaseContentDirectoryProvider> ReleaseContentDirectoryEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn ReleaseContentDirectoryProvider> = provider.clone();
        Self { provider, request_endpoint: ReleaseContentDirectoryRequestEndpoint { provider: request_provider } }
    }
}

impl<P: ReleaseContentDirectoryProvider> NativeRequestEndpoint for ReleaseContentDirectoryEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        READ_RELEASE_CONTENT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            READ_RELEASE_CONTENT_OPERATION => {
                let Ok(request) = request.downcast::<ReadReleaseContentRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read_release_content(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_release_content_directory {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ReleaseContentDirectoryEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_release_content_directory {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_release_content_directory!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct ReleaseContentDirectoryClient {
    read_release_content: NativeRequestHandle<ReleaseContentDirectory>,
}
impl ReleaseContentDirectoryClient {
    pub fn new(handle: NativeRequestHandle<ReleaseContentDirectory>) -> Self {
        Self { read_release_content: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn read_release_content(&self, request: ReadReleaseContentRequest) -> Result<ReadReleaseContentResponse, ReleaseContentDirectoryInvocationError> {
        self.read_release_content.invoke(READ_RELEASE_CONTENT_OPERATION, request).await
            .map_err(ReleaseContentDirectoryInvocationError::Runtime)?
            .map_err(ReleaseContentDirectoryInvocationError::Domain)
    }

    pub async fn read_release_content_with_context(&self, context: InvocationContext, request: ReadReleaseContentRequest) -> Result<ReadReleaseContentResponse, ReleaseContentDirectoryInvocationError> {
        self.read_release_content.invoke_with_context(READ_RELEASE_CONTENT_OPERATION, context, request).await
            .map_err(ReleaseContentDirectoryInvocationError::Runtime)?
            .map_err(ReleaseContentDirectoryInvocationError::Domain)
    }
}

impl CapabilityClient for ReleaseContentDirectoryClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            read_release_content: dependencies.one::<ReleaseContentDirectory>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for ReleaseContentDirectoryClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    read_release_content: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ReleaseContentDirectory>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReleaseContentDirectoryInvocationError {
    Domain(ReadReleaseContentError),
    Runtime(RuntimeFailure),
}
