// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.marketplace.package-directory@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:4e5fac5fcf26780031b29ec034896ccfaf3114a1842832f9308bafaae3592c7b";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const PACKAGE_DIRECTORY_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const PACKAGE_DIRECTORY_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const PACKAGE_DIRECTORY_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const PACKAGE_DIRECTORY_CONTRACT: CapabilityReference<PackageDirectoryClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_package_directory { () => { "{\"capability_id\":\"lenso.marketplace.package-directory@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"read_package\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_package_directory_client {
    () => { "{\"capability_id\":\"lenso.marketplace.package-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.marketplace.package-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_package_directory_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.marketplace.package-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_package_directory_client {
    () => { "{\"capability_id\":\"lenso.marketplace.package-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.marketplace.package-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const READ_PACKAGE_OPERATION: &str = "read_package";

pub use lenso_contract_runtime::{RawJson, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadPackageRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadPackageResponse {
    #[serde(rename = "envelope_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub envelope_json: RawJson,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadPackageError {
    NotPublished,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct PackageDirectory;
impl RequestCapability for PackageDirectory {
    type Request = ReadPackageRequest;
    type Response = ReadPackageResponse;
    type DomainError = ReadPackageError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_PACKAGE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PackageDirectoryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read_package(context, request)
    }
}

impl serde::Serialize for ReadPackageError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::NotPublished => serializer.serialize_str("not_published"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadPackageError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "not_published" => Ok(Self::NotPublished),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_read_package_request(value: &ReadPackageRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_package_request(wire: &str) -> Result<ReadPackageRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_package_response(value: &ReadPackageResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_package_response(wire: &str) -> Result<ReadPackageResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_package_error(value: &ReadPackageError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_package_error(wire: &str) -> Result<ReadPackageError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoPackageDirectoryReadPackageResult {
    fn __lenso_into_result(self) -> Result<Result<ReadPackageResponse, ReadPackageError>, RuntimeFailure>;
}
impl __LensoIntoPackageDirectoryReadPackageResult for Result<ReadPackageResponse, ReadPackageError> {
    fn __lenso_into_result(self) -> Result<Result<ReadPackageResponse, ReadPackageError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPackageDirectoryReadPackageResult for Result<Result<ReadPackageResponse, ReadPackageError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadPackageResponse, ReadPackageError>, RuntimeFailure> { self }
}
impl __LensoIntoPackageDirectoryReadPackageResult for Result<ReadPackageResponse, lenso_plugin_authoring::PluginError<ReadPackageError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadPackageResponse, ReadPackageError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPackageDirectoryReadPackageResult for Result<ReadPackageResponse, PackageDirectoryInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadPackageResponse, ReadPackageError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PackageDirectoryInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PackageDirectoryInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait PackageDirectoryProvider: fmt::Debug + 'static {
    fn read_package(&self, context: InvocationContext, request: ReadPackageRequest) -> NativeRequestFuture<PackageDirectory>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_package_directory {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportPackageDirectory;
        impl $crate::PackageDirectoryProvider for $plugin {
        fn read_package(&self, context: __LensoNativeSupportPackageDirectory::InvocationContext, request: $crate::ReadPackageRequest) -> __LensoNativeSupportPackageDirectory::NativeRequestFuture<$crate::PackageDirectory> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read_package(&plugin, context, request).await;
                $crate::__LensoIntoPackageDirectoryReadPackageResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_package_directory {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportPackageDirectory;
        impl $crate::PackageDirectoryProvider for $object {
        fn read_package(&self, context: __LensoNativeSupportPackageDirectory::InvocationContext, request: $crate::ReadPackageRequest) -> __LensoNativeSupportPackageDirectory::NativeRequestFuture<$crate::PackageDirectory> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::read_package(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoPackageDirectoryReadPackageResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_package_directory {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportPackageDirectory;
        impl $crate::PackageDirectoryProvider for $object {
        fn read_package(&self, context: __LensoNativeSupportPackageDirectory::InvocationContext, request: $crate::ReadPackageRequest) -> __LensoNativeSupportPackageDirectory::NativeRequestFuture<$crate::PackageDirectory> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::PackageDirectoryProvider>::read_package(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct PackageDirectoryRequestEndpoint { provider: Rc<dyn PackageDirectoryProvider> }

#[derive(Debug)]
pub struct PackageDirectoryEndpoint<P: PackageDirectoryProvider> { provider: Rc<P>, request_endpoint: PackageDirectoryRequestEndpoint }
impl<P: PackageDirectoryProvider> PackageDirectoryEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn PackageDirectoryProvider> = provider.clone();
        Self { provider, request_endpoint: PackageDirectoryRequestEndpoint { provider: request_provider } }
    }
}

impl<P: PackageDirectoryProvider> NativeRequestEndpoint for PackageDirectoryEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        READ_PACKAGE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            READ_PACKAGE_OPERATION => {
                let Ok(request) = request.downcast::<ReadPackageRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read_package(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_package_directory {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::PackageDirectoryEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_package_directory {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_package_directory!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct PackageDirectoryClient {
    read_package: NativeRequestHandle<PackageDirectory>,
}
impl PackageDirectoryClient {
    pub fn new(handle: NativeRequestHandle<PackageDirectory>) -> Self {
        Self { read_package: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn read_package(&self, request: ReadPackageRequest) -> Result<ReadPackageResponse, PackageDirectoryInvocationError> {
        self.read_package.invoke(READ_PACKAGE_OPERATION, request).await
            .map_err(PackageDirectoryInvocationError::Runtime)?
            .map_err(PackageDirectoryInvocationError::Domain)
    }

    pub async fn read_package_with_context(&self, context: InvocationContext, request: ReadPackageRequest) -> Result<ReadPackageResponse, PackageDirectoryInvocationError> {
        self.read_package.invoke_with_context(READ_PACKAGE_OPERATION, context, request).await
            .map_err(PackageDirectoryInvocationError::Runtime)?
            .map_err(PackageDirectoryInvocationError::Domain)
    }
}

impl CapabilityClient for PackageDirectoryClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            read_package: dependencies.one::<PackageDirectory>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for PackageDirectoryClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    read_package: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PackageDirectory>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum PackageDirectoryInvocationError {
    Domain(ReadPackageError),
    Runtime(RuntimeFailure),
}
