// Catalog-owned composition using the existing Lenso UI semantic token contract.
import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  aside: {
    borderBlockStartColor: "var(--color-border-secondary)",
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: { "@container (min-width: 640px)": 0, default: 1 },
    borderInlineStartColor: "var(--color-border-secondary)",
    borderInlineStartStyle: "solid",
    borderInlineStartWidth: { "@container (min-width: 640px)": 1, default: 0 },
    minWidth: 0,
    overflowWrap: "anywhere",
    paddingBlockStart: {
      "@container (min-width: 640px)": 0,
      default: "var(--space-4, 16px)",
    },
    paddingInlineStart: {
      "@container (min-width: 640px)": "var(--space-6, 24px)",
      default: 0,
    },
  },
  body: {
    display: "grid",
    gap: "var(--space-6, 24px)",
    gridTemplateColumns: {
      "@container (min-width: 640px)": "minmax(0, 1fr) 208px",
      default: "minmax(0, 1fr)",
    },
  },
  compactAside: {
    borderBlockStartWidth: 1,
    borderInlineStartWidth: 0,
    paddingBlockStart: 16,
    paddingInlineStart: 0,
  },
  compactBody: { gridTemplateColumns: "minmax(0, 1fr)", maxWidth: 640 },
  content: {
    display: "grid",
    flex: "1 1 0%",
    gap: "var(--space-1, 4px)",
    minWidth: 0,
  },
  detailActions: {
    alignItems: {
      "@container (min-width: 640px)": "flex-end",
      default: "flex-start",
    },
    display: "flex",
    flexBasis: { "@container (min-width: 640px)": "auto", default: "100%" },
    flexDirection: "column",
    gap: "var(--space-2, 8px)",
    maxWidth: "100%",
  },
  detailHeader: {
    alignItems: "start",
    borderBottomColor: "var(--color-border-secondary)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexWrap: "wrap",
    gap: "var(--space-4, 16px)",
    marginBottom: "var(--space-4, 16px)",
    paddingBottom: 20,
  },
  detailMedia: {
    alignItems: "center",
    borderRadius: "var(--radius-panel)",
    color: "var(--color-content-secondary)",
    display: "flex",
    flex: "0 0 56px",
    height: "56px",
    justifyContent: "center",
    overflow: "hidden",
  },
  grid: {
    columnGap: "32px",
    display: "grid",
    gridTemplateColumns: {
      "@container (min-width: 640px)": "repeat(2, minmax(0, 1fr))",
      default: "minmax(0, 1fr)",
    },
  },
  header: {
    display: "grid",
    gap: "var(--space-4, 16px)",
    marginBottom: "var(--space-4, 16px)",
  },
  item: {
    alignItems: "center",
    backgroundColor: {
      ":hover": "var(--color-surface-interactive-hover)",
      default: "transparent",
    },
    borderRadius: "var(--radius-panel)",
    boxSizing: "border-box",
    display: "flex",
    gap: "var(--space-4, 16px)",
    marginInline: -12,
    minHeight: "96px",
    minWidth: 0,
    paddingBlock: "var(--space-4, 16px)",
    paddingInline: 12,
  },
  itemActions: {
    alignItems: "flex-end",
    display: "flex",
    flex: "0 0 auto",
    flexDirection: "column",
    gap: "var(--space-2, 8px)",
    maxWidth: "40%",
  },
  link: {
    borderRadius: "var(--radius-control, 8px)",
    color: "inherit",
    display: "grid",
    gap: "var(--space-1, 4px)",
    minWidth: 0,
    textDecoration: "none",
  },
  main: { minWidth: 0, overflowWrap: "anywhere" },
  media: {
    alignItems: "center",
    borderRadius: "var(--radius-panel)",
    color: "var(--color-content-secondary)",
    display: "flex",
    flex: "0 0 56px",
    height: "56px",
    justifyContent: "center",
    overflow: "hidden",
  },
  meta: {
    alignItems: "center",
    color: "var(--color-content-tertiary)",
    display: "flex",
    flexWrap: "wrap",
    fontSize: "var(--catalog-type-caption)",
    gap: "var(--space-2, 8px)",
    lineHeight: 1.5,
    minWidth: 0,
    overflowWrap: "anywhere",
  },
  name: {
    fontSize: "var(--catalog-type-name)",
    fontWeight: 600,
    lineHeight: 1.5,
    margin: 0,
    overflowWrap: "anywhere",
  },
  paragraph: {
    color: "var(--color-content-secondary)",
    fontSize: "var(--catalog-type-body)",
    lineHeight: 1.5,
    margin: "0 0 12px",
    maxWidth: "68ch",
    overflowWrap: "anywhere",
    textWrap: "pretty",
  },
  root: {
    color: "var(--color-content-primary)",
    containerType: "inline-size",
    fontFamily: "var(--font-sans)",
    minWidth: 0,
    width: "100%",
  },
  sectionTitle: {
    fontSize: "var(--catalog-type-section)",
    fontWeight: 600,
    lineHeight: 1.5,
    margin: "0 0 12px",
  },
  summary: {
    color: "var(--color-content-secondary)",
    fontSize: "var(--catalog-type-body)",
    lineHeight: 1.5,
    margin: 0,
    overflowWrap: "anywhere",
    textWrap: "pretty",
  },
  title: {
    fontSize: "var(--catalog-type-title)",
    fontWeight: 600,
    letterSpacing: "-0.025em",
    lineHeight: 1.2,
    margin: 0,
    overflowWrap: "anywhere",
    textWrap: "balance",
  },
  toolbar: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "var(--space-2, 8px)",
    minWidth: 0,
  },
});
