// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.marketplace.linked-directory@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:389acda948ac0497921718013b4969ef99d57dc465333050323fb5c905515588";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const LINKED_DIRECTORY_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const LINKED_DIRECTORY_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const LINKED_DIRECTORY_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const LINKED_DIRECTORY_CONTRACT: CapabilityReference<LinkedDirectoryClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_linked_directory { () => { "{\"capability_id\":\"lenso.marketplace.linked-directory@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"read_linked_cargo\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_linked_directory_client {
    () => { "{\"capability_id\":\"lenso.marketplace.linked-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.marketplace.linked-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_linked_directory_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.marketplace.linked-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_linked_directory_client {
    () => { "{\"capability_id\":\"lenso.marketplace.linked-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.marketplace.linked-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const READ_LINKED_CARGO_OPERATION: &str = "read_linked_cargo";

pub use lenso_contract_runtime::{RawJson, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadLinkedCargoRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadLinkedCargoResponse {
    #[serde(rename = "envelope_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub envelope_json: RawJson,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadLinkedCargoError {
    NotPublished,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct LinkedDirectory;
impl RequestCapability for LinkedDirectory {
    type Request = ReadLinkedCargoRequest;
    type Response = ReadLinkedCargoResponse;
    type DomainError = ReadLinkedCargoError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_LINKED_CARGO_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<LinkedDirectoryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read_linked_cargo(context, request)
    }
}

impl serde::Serialize for ReadLinkedCargoError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::NotPublished => serializer.serialize_str("not_published"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadLinkedCargoError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "not_published" => Ok(Self::NotPublished),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_read_linked_cargo_request(value: &ReadLinkedCargoRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_linked_cargo_request(wire: &str) -> Result<ReadLinkedCargoRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_linked_cargo_response(value: &ReadLinkedCargoResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_linked_cargo_response(wire: &str) -> Result<ReadLinkedCargoResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_linked_cargo_error(value: &ReadLinkedCargoError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_linked_cargo_error(wire: &str) -> Result<ReadLinkedCargoError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoLinkedDirectoryReadLinkedCargoResult {
    fn __lenso_into_result(self) -> Result<Result<ReadLinkedCargoResponse, ReadLinkedCargoError>, RuntimeFailure>;
}
impl __LensoIntoLinkedDirectoryReadLinkedCargoResult for Result<ReadLinkedCargoResponse, ReadLinkedCargoError> {
    fn __lenso_into_result(self) -> Result<Result<ReadLinkedCargoResponse, ReadLinkedCargoError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoLinkedDirectoryReadLinkedCargoResult for Result<Result<ReadLinkedCargoResponse, ReadLinkedCargoError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadLinkedCargoResponse, ReadLinkedCargoError>, RuntimeFailure> { self }
}
impl __LensoIntoLinkedDirectoryReadLinkedCargoResult for Result<ReadLinkedCargoResponse, lenso_plugin_authoring::PluginError<ReadLinkedCargoError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadLinkedCargoResponse, ReadLinkedCargoError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoLinkedDirectoryReadLinkedCargoResult for Result<ReadLinkedCargoResponse, LinkedDirectoryInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadLinkedCargoResponse, ReadLinkedCargoError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(LinkedDirectoryInvocationError::Domain(error)) => Ok(Err(error)),
            Err(LinkedDirectoryInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait LinkedDirectoryProvider: fmt::Debug + 'static {
    fn read_linked_cargo(&self, context: InvocationContext, request: ReadLinkedCargoRequest) -> NativeRequestFuture<LinkedDirectory>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_linked_directory {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportLinkedDirectory;
        impl $crate::LinkedDirectoryProvider for $plugin {
        fn read_linked_cargo(&self, context: __LensoNativeSupportLinkedDirectory::InvocationContext, request: $crate::ReadLinkedCargoRequest) -> __LensoNativeSupportLinkedDirectory::NativeRequestFuture<$crate::LinkedDirectory> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read_linked_cargo(&plugin, context, request).await;
                $crate::__LensoIntoLinkedDirectoryReadLinkedCargoResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_linked_directory {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportLinkedDirectory;
        impl $crate::LinkedDirectoryProvider for $object {
        fn read_linked_cargo(&self, context: __LensoNativeSupportLinkedDirectory::InvocationContext, request: $crate::ReadLinkedCargoRequest) -> __LensoNativeSupportLinkedDirectory::NativeRequestFuture<$crate::LinkedDirectory> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::read_linked_cargo(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoLinkedDirectoryReadLinkedCargoResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_linked_directory {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportLinkedDirectory;
        impl $crate::LinkedDirectoryProvider for $object {
        fn read_linked_cargo(&self, context: __LensoNativeSupportLinkedDirectory::InvocationContext, request: $crate::ReadLinkedCargoRequest) -> __LensoNativeSupportLinkedDirectory::NativeRequestFuture<$crate::LinkedDirectory> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::LinkedDirectoryProvider>::read_linked_cargo(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct LinkedDirectoryRequestEndpoint { provider: Rc<dyn LinkedDirectoryProvider> }

#[derive(Debug)]
pub struct LinkedDirectoryEndpoint<P: LinkedDirectoryProvider> { provider: Rc<P>, request_endpoint: LinkedDirectoryRequestEndpoint }
impl<P: LinkedDirectoryProvider> LinkedDirectoryEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn LinkedDirectoryProvider> = provider.clone();
        Self { provider, request_endpoint: LinkedDirectoryRequestEndpoint { provider: request_provider } }
    }
}

impl<P: LinkedDirectoryProvider> NativeRequestEndpoint for LinkedDirectoryEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        READ_LINKED_CARGO_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            READ_LINKED_CARGO_OPERATION => {
                let Ok(request) = request.downcast::<ReadLinkedCargoRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read_linked_cargo(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_linked_directory {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::LinkedDirectoryEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_linked_directory {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_linked_directory!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct LinkedDirectoryClient {
    read_linked_cargo: NativeRequestHandle<LinkedDirectory>,
}
impl LinkedDirectoryClient {
    pub fn new(handle: NativeRequestHandle<LinkedDirectory>) -> Self {
        Self { read_linked_cargo: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn read_linked_cargo(&self, request: ReadLinkedCargoRequest) -> Result<ReadLinkedCargoResponse, LinkedDirectoryInvocationError> {
        self.read_linked_cargo.invoke(READ_LINKED_CARGO_OPERATION, request).await
            .map_err(LinkedDirectoryInvocationError::Runtime)?
            .map_err(LinkedDirectoryInvocationError::Domain)
    }

    pub async fn read_linked_cargo_with_context(&self, context: InvocationContext, request: ReadLinkedCargoRequest) -> Result<ReadLinkedCargoResponse, LinkedDirectoryInvocationError> {
        self.read_linked_cargo.invoke_with_context(READ_LINKED_CARGO_OPERATION, context, request).await
            .map_err(LinkedDirectoryInvocationError::Runtime)?
            .map_err(LinkedDirectoryInvocationError::Domain)
    }
}

impl CapabilityClient for LinkedDirectoryClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            read_linked_cargo: dependencies.one::<LinkedDirectory>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for LinkedDirectoryClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    read_linked_cargo: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<LinkedDirectory>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum LinkedDirectoryInvocationError {
    Domain(ReadLinkedCargoError),
    Runtime(RuntimeFailure),
}
